#trigger:
 # branches:
  #  include:
   # - master
  #paths:
   # include:
    #- function1

trigger:
- none

resources:
  repositories:
  - repository: MultiPrj-Containerize-Poc.git
    type: git
    name: demoprj/MultiPrj-Containerize-Poc.git
    ref: main
    trigger:
      branches:
       include:
       - master
      paths:
       include:
       - function1

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default
      demand: java

    steps:
    - checkout: MultiPrj-Containerize-Poc.git
      fetchDepth: 1
      persistCredentials: true

    - task: PowerShell@2
      displayName: displaying the checkout
      inputs: 
          targetType: 'inline'
          script: |
           pwd
           echo "*********"
           cd $(System.DefaultWorkingDirectory)
           pwd
           echo "*********"
           ls

    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
         command: restore
         projects: '*/.csproj'
         #restoreArguments: 'p:Configuration=Release'
         workingDirectory: ./function1

    - task: DotNetCoreCLI@2
      displayName: 'dotnet publish'
      inputs:
         command: publish
         projects: '*/.csproj'
         #restoreArguments: 'p:Configuration=Release'
         workingDirectory: ./function1
         #arguments: '-r linux-x64 -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)'